### ISSUE TITLE
Users should be able to see who is in chat with them.

### ISSUE THREAD

**Issue by JakeCooper** [JakeCooper/nwHack2015#10]
Again, title. Not sure where we can put this though, maybe off to the side of the current chat a bit? @bitHero could you possibly make an HTML design for it so we don't massacre your beautiful chat window?

**Comment by ChrisHampu** [comment]
What if there were a sub header under the header that holds the title and description. It could have the current users name. And when you click it, it extends upwards and has a scrolly box that holds all the users in chat by name and icon. And they are clickable

**Comment by JakeCooper** [comment]
Added the settings/people tab. edb4502
