### ISSUE TITLE
Locale Radius

### ISSUE THREAD

**Issue by ChrisHampu** [JakeCooper/nwHack2015#14]
Users should be able to personalize locales such as setting how much radius they should cover. E.g radius between 10 meters and 1km. A slider could determine the radius. There could a pin dropped with a circle to simulate the affected radius on the map while the radius is being selected/moved.

**Comment by JakeCooper** [comment]
Privacy of locales already has an open issue. #11. Rolled your privacy part into it. Also this probably deserves its own issue as its a lot of work.

**Comment by ChrisHampu** [comment]
I rewrote my issue to just cover the radius portion of the request.

**Comment by JakeCooper** [comment]
https://github.com/seiyria/bootstrap-slider

Use this for the radius, but take the JS, don't import the whole thing.
