### ISSUE TITLE
Clicking on a users name in chat should link to their profile.

### ISSUE THREAD

**Issue by JakeCooper** [JakeCooper/nwHack2015#9]
If we want to connect users, we should allow them to become friends on facebook. Hopefully the facebook API passes that back and then we can just throw it into the HTML.

**Comment by ChrisHampu** [comment]
We need to make a window so users can actually get a proper overview of who's in chat, even if they aren't sending messages. Name, and other info we have on them. And then yeah, upon clicking take you to their fb page. Fb api should allow this.

**Comment by JakeCooper** [comment]
@ChrisHampu Turned that into its own separate issue, but also we should allow people to click names and display pictures. The more access the merrier :D.

Also we may want to consider adding a profile page, unless we're gonna stick with Facebook only auth, which might not be the best route.

**Comment by hwkr** [comment]
Oops nvm, should read better

**Comment by hwkr** [comment]
Also for UX/design stuff like this we should maybe nail it down before we just tear though features
